services:
  backend:
    build: ./backend
    ports:
      - "8080:3000"
    environment:
      # DATABASE_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-development_only}@postgres:5432/duogradus?schema=public"
      DATABASE_URL: "file:/usr/src/app/database/database.sqlite"
    networks:
      - backend
    volumes:
      - database:/usr/src/app/database
      - ${PWD}/.env/usr/src/app/.env
  webserver:
    build: ./frontend
    ports:
      - "8000:8000"
    networks:
      - backend
  # postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-development_only}
  #     POSTGRES_DB: duogradus
  #     PGDATA: /data/postgres
  #   volumes:
  #     - postgres:/data/postgres
  #   networks:
  #     - backend
  #   restart: always

networks:
  backend:

# volumes:
#   postgres:
volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/database
      o: bind
