title: 'Week [Woche] ([Jahr] KW [Kalenderwoche], [Startdatum]-[Enddatum])'
body:
  - type: dropdown
    attributes:
      label: 'Aktueller Status: '
      options:
        - 🟥
        - 🟨
        - 🟩
      default: 2
    validations:
      required: true
  - type: textarea
    attributes:
      label: '✅ Was ist diese Woche passiert?'
      placeholder: |
        - 
        -
  - type: textarea
    attributes:
      label: '👣 Was sind die nächsten Schritte?'
      placeholder: |
        - 
        -
  - type: textarea
    attributes:
      label: '🤺 Was waren/sind eventuelle Hindernisse?'
      placeholder: |
        - 
        -
  - type: textarea
    attributes:
      label: '💡 Was waren die Erkenntnisse dieser Woche?'
      placeholder: |
        - 
        -
