title: "Week [Woche] ([Jahr] KW [Kalenderwoche], [Startdatum]-[Enddatum])"
body:
  - type: dropdown
  attributes:
    label: "Aktueller Status: "
    options:
      - 🟥
      - 🟨
      - 🟩
    default: 2
  validations:
    required: true
  - type: textarea
  attributes:
    label: "### ✅ Was ist diese Woche passiert?"
    placeholder: |
      - 
      - 
      - 
  - type: textarea
  attributes:
    label: "### 👣 Was sind die nächsten Schritte?"
    value: "- "
  - type: textarea
  attributes:
    label: "### 🤺 Was waren/sind eventuelle Hindernisse?"
    value: "- "
  - type: textarea
  attributes:
    label: "### 💡 Was waren die Erkenntnisse dieser Woche?"
    value: "- "
  
