name: Docs

on:
  pull_request_target:
    branches:
      - main

jobs:
  verify:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run check format
        run: cd docs && npm run check:format
